### ISSUE TITLE
Big data set causing R to crash when using "identify_neighbourhoods" with "hierarchical" method

### ISSUE THREAD

**Issue by ayhanxian** [TrigosTeam/SPIAT#28]
Hi Yuzhou,

When executing the function "identify_neighbourhoods" using the method "hierarchical" on a large dataset (~500,000 rows observation(, R would crash.

**Comment by fuerzhou** [comment]
Hi @ayhanxian,

If you encounter memory issue, try adjusting the Rstudio memory limit by changing the R_MAX_VSIZE variable in the .Renviron file. Please refer to [this thread on Stackoverflow](https://stackoverflow.com/questions/51295402/r-on-macos-error-vector-memory-exhausted-limit-reached).

Alternatively, you could use "dbscan" instead of "hierarchical" method. Please exploring different parameter values that work best for you dataset.

Yuzhou
