### ISSUE TITLE
NA result of crossing_of_crossK() function

### ISSUE THREAD

**Issue by navern0net** [TrigosTeam/SPIAT#39]
Hi there,

Firstly, thanks for your package, it's super helpful and relatively quick.

What could be the reason behind NA after running crossing_of_crossK function? AUC_of_cross_function gives the number, but not the crossing_of_crossK.
![image](https://github.com/user-attachments/assets/743cb45c-1234-4206-97be-3fc5ada7d269)

Thanks!

**Comment by fuerzhou** [comment]
Hi @navern0net,

Thank you for your interest in the package.

There are cases when we think the CKI (crossing of cross K) scores do not mean anything and we let the function give NA. Please refer to the Methods section and Supp Figure 3 of the paper [10.1038/s41467-023-37822-0](https://www.nature.com/articles/s41467-023-37822-0) for details. 

It perhaps makes more sense to let the function return a number instead of NA and let users decide how to interpret it, which we will consider.

Yuzhou

**Comment by navern0net** [comment]
Hi Yuzhou,

Thanks for your reply. 
If my understanding is correct, NA means "no ring pattern present" as x1 was lower than 0.04, right? 
If so, it would be super handy to have this information in the function documentation (less guessing for users). As of now it looks like I've made a mistake somewhere and didn't get the results from the function.

Many thanks for your explanation and consideration,
Ilariya

**Comment by fuerzhou** [comment]
Yes it makes sense. Thank you for the suggestion, we'll make the change in the next update.
