### ISSUE TITLE
Predict_phenotypes does not plot density plots

### ISSUE THREAD

**Issue by Art-Ink** [TrigosTeam/SPIAT#41]
For some time predict_phenotypes() does no longer print the density plots.

I am on R 4.4.1, using SPIAT 1.6.3 and when I run the examples for this function it also does not print the plots.

Does anyone have an idea why this is?

**Comment by fuerzhou** [comment]
Hi @Art-Ink,

Thank you for the feedback. This is due to a mistake in the code that missed printing out the plots when the parameter `reference_phenotypes` is `TRUE`. 

I have fixed this in the newer version (`devel`) branch on Github. It's not be updated in the current release version. A workaround to print the plots out with your current version is to set the parameter `predict_phenotypes` to `FALSE`. This is just to print the plots and please still use your own parameter setting in your analysis.

Yuzhou

**Comment by Art-Ink** [comment]
Hi Yuzhou

Thank you for the quick reply, that is good to know.

Christian
