### ISSUE TITLE
Scatter Plot not generating

### ISSUE THREAD

**Issue by yuvibim08** [TrigosTeam/SPIAT#9]
Using SPIAT for a inForm data analysis.

issue1: Scatter plot is not generating
            command given: plot_cell_marker_levels(image,"PDL1+")
            error: Error in parse(text = marker) : <text>:2:0: unexpected end of input
                     1: PDL1+
            command given: plot_cell_marker_levels(SPIAT::image,"panCK+")
            error: Error in h(simpleError(msg, call)) : 
                      error in evaluating the argument 'x' in selecting a method for function 'assay': 'image' is not an exported object from 
                      'namespace:SPIAT'
![scatter_plot_error - Copy](https://user-images.githubusercontent.com/89310281/184142501-f6e25909-0166-45dc-a6a4-b8b4508af543.png)

**Comment by fuerzhou** [comment]
Hi @yuvibim08 , 
Thank you for raising the issue. Could you please provide a slice of your data (the original table or the formatted image) so that I can identify the issue? If concerned about the data safety, you could potentially provide the object names and the column names in your object.
If you can not provide example data, I suggest checking your marker names. Try marker names without "+", for example, only using "PDL1" or "panCK". Another issue is that "image" is not from "SPIAT" package, so `SPIAT::image` will cause error.
Please let me know how it goes.
Thanks!

**Comment by yuvibim08** [comment]
Thank you for your reply, I will contact you through the mail.

**Comment by fuerzhou** [comment]
The error was due to passing wrong marker names into the function. The marker names should not contain "+".
